### ISSUE TITLE
handling reference TE when they are not annotated by repeatMasker

### ISSUE THREAD

**Issue by Anwica** [JinfengChen/RelocaTE2#12]
1. What does it output when TE is actually present in reference but is not annotated by repeat-masker. Do you consider those as non-reference TE? I want to find all the TEs irrespective of their presence/absence in reference. 
2. Does it work for unpaired reads?

**Comment by JinfengChen** [comment]
Sorry for the late reply. Apologize.

On Sun, Jul 29, 2018 at 8:29 AM, Anwica <notifications@github.com> wrote:

>
>    1. What does it output when TE is actually present in reference but is
>    not annotated by repeat-makser. Do you consider those as non-reference TE?
>    I want to find all the TEs irrespective of their presence/absence in
>    reference.
>
> RelocaTE2 intends to remove these reads and calls based on the annotaion
of reference TEs. If TEs are present in the preference but are not
annotated good enough. There is little chance that you may get false
positive calls because of inproperly mapped reads at these TE insertion
sites. RelocaTE2 call a insertion only if the insertion has paired-end
reads supporting the insertion from both ends. Normally, the reference TEs
would not have these reads from both direction unless they are mapped
incorrectly.


>
>    1. Does it work for unpaired reads?
>
> RelocaTE2 does not work well with unpaired reads. RelocaTE can use
unpaired reads but may generate many false positive calls.
